name: artifact_deployed

on:
  # workflow_dispatch é obrigatório, para que o Artifactory possa disparar
  # o fluxo de trabalho através da API REST do GitHub.
  workflow_dispatch: 
    # as entradas são opcionais, podem ser usadas para transmitir dados contextuais
    # do evento JFrog para o fluxo de trabalho.
    inputs:
      artifact_path: 
        required: true 
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print artifact_path
        run: echo  The path is ${{ inputs.artifact_path }} 
