name: Webhook Action

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  print_id:
    runs-on: ubuntu-latest
    steps:
      - name: Gam ID
        run: 'echo "The Gam ID is ${{ github.event.client_payload.gam_id }}"'