name: Webhook Action

on:
  repository_dispatch:
    types:
      - webhook
    inputs:
      id:
        description: 'ID to print'
        required: true
        default: '12345'

jobs:
  print_id:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "Event of type: $GITHUB_EVENT_NAME"
      - name: Print ID
        run: echo "The ID is ${{ github.event.client_payload.id  }}"