name: Webhook Action

on:
  workflow_dispatch:
    types:
      - webhook
    inputs:
      id:
        description: 'ID to print'
        required: true
        default: '12345'

jobs:
  print_id:
    runs-on: ubuntu-latest
    steps:
      - name: Print ID
        run: echo "The ID is ${{ github.event.inputs.id }}"