name: Update branch with master

on:
  pull_request:
    types: [synchronize]

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge master into PR branch
        run: |
          git fetch origin master
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge origin/master
          git push origin ${{ github.event.pull_request.head.ref }}
